# Generated by Django 4.0.2 on 2022-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Age',
            field=models.CharField(max_length=3, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=12, null=True, verbose_name='ZIP'),
        ),
    ]
