# Generated by Django 4.0.1 on 2022-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alleducation_allexperience_allsector_allsponsor_allvote_anonymoususer_education_experience_represent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectedOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.IntegerField(max_length=100)),
                ('senate_class', models.IntegerField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('contact_form', models.CharField(max_length=250)),
                ('rss_url', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('youtube', models.CharField(max_length=250)),
                ('youtube_id', models.CharField(max_length=250)),
                ('bioguide_id', models.CharField(max_length=250)),
                ('thomas_id', models.CharField(max_length=250)),
                ('opensecrets_id', models.CharField(max_length=250)),
                ('lis_id', models.CharField(max_length=250)),
                ('fec_ids', models.CharField(max_length=250)),
                ('cspan_id', models.CharField(max_length=250)),
                ('govtrack_id', models.CharField(max_length=250)),
                ('votesmart_id', models.CharField(max_length=250)),
                ('ballotpedia_id', models.CharField(max_length=250)),
                ('washington_post_id', models.CharField(max_length=250)),
                ('icpsr_id', models.CharField(max_length=250)),
                ('wikipedia_id', models.CharField(max_length=250)),
            ],
        ),
    ]
