# Generated by Django 3.2.4 on 2022-03-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alleducation_allexperience_allsector_allsponsor_allvote_anonymoususer_education_experience_represent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, null=True, verbose_name='Bill Number')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('outcome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vote Result')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('sRoll', models.CharField(blank=True, max_length=200, null=True, verbose_name='sRoll')),
                ('hrRoll', models.CharField(blank=True, max_length=200, null=True, verbose_name='hrRoll')),
                ('category1', models.CharField(blank=True, max_length=200, null=True, verbose_name='category1')),
                ('organizationSponsor1', models.CharField(blank=True, max_length=200, null=True, verbose_name=' Sponsor1')),
                ('organizationSponsor2', models.CharField(blank=True, max_length=200, null=True, verbose_name=' Sponsor2')),
                ('organizationSponsor3', models.CharField(blank=True, max_length=200, null=True, verbose_name=' Sponsor3')),
                ('organizationSponsor4', models.CharField(blank=True, max_length=200, null=True, verbose_name=' Sponsor4')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(blank=True, null=True, verbose_name='Roll')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('voteCast', models.CharField(max_length=50, null=True, verbose_name='Vote Cast')),
            ],
        ),
        migrations.RemoveField(
            model_name='allexperience',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='allexperience',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='allsector',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='allsector',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='allsponsor',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='allsponsor',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='allvote',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='allvote',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='homecity',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='representativetown',
        ),
        migrations.AddField(
            model_name='represent',
            name='district',
            field=models.IntegerField(blank=True, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='represent',
            name='servicescore',
            field=models.IntegerField(blank=True, null=True, verbose_name='Service Score'),
        ),
        migrations.AddField(
            model_name='represent',
            name='state',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='representative',
            name='officeaddress',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='representative',
            name='phone',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='representative',
            name='type',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='anonymous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='party',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Party'),
        ),
        migrations.DeleteModel(
            name='AllEducation',
        ),
        migrations.DeleteModel(
            name='AllExperience',
        ),
        migrations.DeleteModel(
            name='AllSector',
        ),
        migrations.DeleteModel(
            name='AllSponsor',
        ),
        migrations.DeleteModel(
            name='AllVote',
        ),
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='votes',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.representative'),
        ),
        migrations.AddField(
            model_name='votes',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bill'),
        ),
    ]
