# Generated by Django 3.2.4 on 2022-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220325_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='voteCast',
            field=models.CharField(max_length=3, null=True, verbose_name='Vote Cast'),
        ),
    ]
