# Generated by Django 4.0.1 on 2022-03-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_electedofficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electedofficial',
            name='district',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='senate_class',
            field=models.IntegerField(),
        ),
    ]
