# Generated by Django 3.2.4 on 2022-03-26 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_votes_votecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, verbose_name='Committee Number')),
                ('category', models.CharField(max_length=200, null=True, verbose_name='Category ')),
                ('hrname', models.CharField(blank=True, max_length=250, null=True, verbose_name='House Committee Name')),
                ('sname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Senate Committee Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='LastName')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='FirstName')),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='internationalaffairs',
            new_name='international_affairs',
        ),
        migrations.RenameField(
            model_name='representative',
            old_name='internationalaffairs',
            new_name='international_affairs',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='organizationSponsor1',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='organizationSponsor2',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='organizationSponsor3',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='organizationSponsor4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='agriculture_and_food',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='armedforces_and_nationalsecurity',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='civilrights_and_liberties_minorityissues',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='crime_and_lawenforcement',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='economics_and_public_finance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='emergency_management',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='environmental_protection',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='governmentoperations_and_politics',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='health',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='immigration',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='labor_and_employment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='science_technology_communications',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='social_welfare',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='taxation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='transportation_and_public_works',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='represent',
            name='district',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='agriculture_and_food',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='armedforces_and_nationalsecurity',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='civilrights_and_liberties_minorityissues',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='crime_and_lawenforcement',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='economics_and_public_finance',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='emergency_management',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='environmental_protection',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='governmentoperations_and_politics',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='health',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='immigration',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='labor_and_employment',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='science_technology_communications',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='social_welfare',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='taxation',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='transportation_and_public_works',
        ),
        migrations.AddField(
            model_name='customer',
            name='Science',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Science'),
        ),
        migrations.AddField(
            model_name='customer',
            name='energy_and_environment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Energy and Environment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='food_and_agriculture',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Food and Agriculture'),
        ),
        migrations.AddField(
            model_name='customer',
            name='government',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Government'),
        ),
        migrations.AddField(
            model_name='customer',
            name='healthcare_and_medicare',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Healthcare and Medicare'),
        ),
        migrations.AddField(
            model_name='customer',
            name='housing_and_labor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Housing and Labor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='military',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Military'),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='socialsecurity_or_unemployment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Social Security or Unemployment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_line1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_line2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='transportation_and_infrastructure',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Transportation and Infrastructure'),
        ),
        migrations.AddField(
            model_name='customer',
            name='veteran_affairs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Veteran's Affairs"),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ZIP code'),
        ),
        migrations.AddField(
            model_name='representative',
            name='Science',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Science'),
        ),
        migrations.AddField(
            model_name='representative',
            name='district',
            field=models.IntegerField(blank=True, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='representative',
            name='energy_and_environment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Energy and Environment'),
        ),
        migrations.AddField(
            model_name='representative',
            name='food_and_agriculture',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Food and Agriculture'),
        ),
        migrations.AddField(
            model_name='representative',
            name='government',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Government'),
        ),
        migrations.AddField(
            model_name='representative',
            name='healthcare_and_medicare',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Healthcare and Medicare'),
        ),
        migrations.AddField(
            model_name='representative',
            name='housing_and_labor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Housing and Labor'),
        ),
        migrations.AddField(
            model_name='representative',
            name='military',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Military'),
        ),
        migrations.AddField(
            model_name='representative',
            name='socialsecurity_or_unemployment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Social Security or Unemployment'),
        ),
        migrations.AddField(
            model_name='representative',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='representative',
            name='transportation_and_infrastructure',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Transportation and Infrastructure'),
        ),
        migrations.AddField(
            model_name='representative',
            name='veteran_affairs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Veteran's Affairs"),
        ),
        migrations.AlterField(
            model_name='bill',
            name='hrRoll',
            field=models.IntegerField(blank=True, null=True, verbose_name='House Roll'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sRoll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Senate Vote Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bill')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Committees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bill')),
                ('committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.committee')),
            ],
        ),
    ]
