# Generated by Django 4.0.1 on 2022-03-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_electedofficial_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electedofficial',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='ballotpedia_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='birthday',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='contact_form',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='cspan_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='district',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='facebook',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='fec_ids',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='govtrack_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='icpsr_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='lis_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='opensecrets_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='party',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='rss_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='senate_class',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='suffix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='thomas_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='twitter',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='votesmart_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='washington_post_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='wikipedia_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='youtube',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='electedofficial',
            name='youtube_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
