# Generated by Django 3.2.4 on 2022-04-18 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220326_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.CharField(max_length=200, null=True)),
                ('rate', models.FloatField(default=None, null=True, verbose_name='Rate')),
                ('issue', models.CharField(choices=[('None', 'None'), ('User Interface', 'User Interface'), ('Navigation ', 'Navigation'), ('Other', 'Other')], max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Membership',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('thomas_id', models.CharField(max_length=100, null=True)),
        #         ('name', models.CharField(max_length=200, null=True)),
        #         ('rank', models.IntegerField(null=True)),
        #         ('bioguide_id', models.CharField(max_length=100, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TestBill',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('bill_tag', models.CharField(max_length=250, null=True)),
        #         ('number', models.IntegerField(null=True)),
        #         ('chamber', models.CharField(max_length=100, null=True)),
        #         ('committee', models.CharField(max_length=100, null=True)),
        #         ('sponsor', models.CharField(max_length=100, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TestElectedOfficial',
        #     fields=[
        #         ('last_name', models.CharField(max_length=100, null=True)),
        #         ('first_name', models.CharField(max_length=100, null=True)),
        #         ('middle_name', models.CharField(max_length=100, null=True)),
        #         ('suffix', models.CharField(max_length=100, null=True)),
        #         ('nickname', models.CharField(max_length=100, null=True)),
        #         ('full_name', models.CharField(max_length=100, null=True)),
        #         ('birthday', models.DateField(max_length=100, null=True)),
        #         ('gender', models.CharField(max_length=100, null=True)),
        #         ('type', models.CharField(max_length=100, null=True)),
        #         ('state', models.CharField(max_length=100, null=True)),
        #         ('district', models.IntegerField(null=True)),
        #         ('senate_class', models.IntegerField(null=True)),
        #         ('party', models.CharField(max_length=100, null=True)),
        #         ('url', models.CharField(max_length=250, null=True)),
        #         ('address', models.CharField(max_length=250, null=True)),
        #         ('phone', models.CharField(max_length=100, null=True)),
        #         ('contact_form', models.CharField(max_length=250, null=True)),
        #         ('rss_url', models.CharField(max_length=250, null=True)),
        #         ('twitter', models.CharField(max_length=250, null=True)),
        #         ('facebook', models.CharField(max_length=250, null=True)),
        #         ('youtube', models.CharField(max_length=250, null=True)),
        #         ('youtube_id', models.CharField(max_length=250, null=True)),
        #         ('bioguide_id', models.CharField(default=999, max_length=250, primary_key=True, serialize=False)),
        #         ('thomas_id', models.CharField(max_length=250, null=True)),
        #         ('opensecrets_id', models.CharField(max_length=250, null=True)),
        #         ('lis_id', models.CharField(max_length=250, null=True)),
        #         ('fec_ids', models.CharField(max_length=250, null=True)),
        #         ('cspan_id', models.CharField(max_length=250, null=True)),
        #         ('govtrack_id', models.CharField(max_length=250, null=True)),
        #         ('votesmart_id', models.CharField(max_length=250, null=True)),
        #         ('ballotpedia_id', models.CharField(max_length=250, null=True)),
        #         ('washington_post_id', models.CharField(max_length=250, null=True)),
        #         ('icpsr_id', models.CharField(max_length=250, null=True)),
        #         ('wikipedia_id', models.CharField(max_length=250, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TestVote',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('voter_id', models.CharField(max_length=100, null=True)),
        #         ('state', models.CharField(max_length=100, null=True)),
        #         ('bill_type', models.CharField(max_length=100, null=True)),
        #         ('number', models.IntegerField(null=True)),
        #         ('roll', models.IntegerField(null=True)),
        #         ('value', models.CharField(max_length=100, null=True)),
        #         ('result', models.CharField(max_length=100, null=True)),
        #         ('chamber', models.CharField(max_length=100, null=True)),
        #         ('sess', models.IntegerField(null=True)),
        #         ('yr', models.IntegerField(null=True)),
        #         ('category', models.CharField(max_length=100, null=True)),
        #         ('type_vote', models.CharField(max_length=100, null=True)),
        #     ],
        # ),
        # migrations.RenameField(
        #     model_name='customer',
        #     old_name='Science',
        #     new_name='science',
        # ),
        # migrations.RemoveField(
        #     model_name='committee',
        #     name='category',
        # ),
        # migrations.RemoveField(
        #     model_name='committee',
        #     name='hrname',
        # ),
        # migrations.RemoveField(
        #     model_name='committee',
        #     name='number',
        # ),
        # migrations.RemoveField(
        #     model_name='committee',
        #     name='sname',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='education',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='energy_and_environment',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='food_and_agriculture',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='government',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='healthcare_and_medicare',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='housing_and_labor',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='military',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='socialsecurity_or_unemployment',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='transportation_and_infrastructure',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='veteran_affairs',
        # ),
        # migrations.AddField(
        #     model_name='committee',
        #     name='chamber',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='committee',
        #     name='committee_id',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='committee',
        #     name='name',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='committee',
        #     name='thomas_id',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='agriculture',
        #     field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='defense_and_intelligence',
        #     field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Defense and Intelligence'),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='district',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='education_and_labor',
        #     field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Education and Labor'),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='energy',
        #     field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Energy'),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='environment',
        #     field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Environment'),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='healthcare',
        #     field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Healthcare'),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='infrastructure',
        #     field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Infrastructure'),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='military_and_veterans',
        #     field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Military and Veterans'),
        # ),
        # migrations.DeleteModel(
        #     name='Committees',
        # ),
    ]
