# Generated by Django 4.0.1 on 2022-03-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_electedofficial_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electedofficial',
            name='bioguide_id',
            field=models.CharField(default=999, max_length=250, primary_key=True, serialize=False),
        ),
    ]
