# Generated by Django 4.0.1 on 2022-03-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_electedofficial_bioguide_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('bill_type', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('value', models.CharField(max_length=100, null=True)),
                ('result', models.CharField(max_length=100, null=True)),
                ('chamber', models.CharField(max_length=100, null=True)),
                ('sess', models.IntegerField()),
                ('yr', models.IntegerField()),
                ('category', models.CharField(max_length=100, null=True)),
                ('type_vote', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ElectedOfficial',
            new_name='TestElectedOfficial',
        ),
    ]
