# Generated by Django 4.0.1 on 2022-03-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_testvotes_rename_electedofficial_testelectedofficial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestVotes',
            new_name='TestVote',
        ),
    ]
