# Generated by Django 4.0.1 on 2022-03-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_testvotes_testvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvote',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='testvote',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='testvote',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testvote',
            name='roll',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testvote',
            name='sess',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testvote',
            name='yr',
            field=models.IntegerField(null=True),
        ),
    ]
