# Generated by Django 4.0.1 on 2022-03-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_testvote_updated_alter_testvote_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testvote',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='testvote',
            name='updated',
        ),
    ]
