# Generated by Django 4.0.1 on 2022-03-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220326_1838'),
        ('accounts', '0017_remove_testvote_datetime_remove_testvote_updated'),
    ]

    operations = [
    ]
