# Generated by Django 4.0.1 on 2022-03-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20220326_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBills',
            fields=[
                ('bill_id', models.CharField(default=0, max_length=100, primary_key=True, serialize=False)),
                ('sponsor_1', models.CharField(max_length=100, null=True)),
                ('sponsor_2', models.CharField(max_length=100, null=True)),
                ('sponsor_3', models.CharField(max_length=100, null=True)),
                ('committee_1', models.CharField(max_length=100, null=True)),
                ('committee_2', models.CharField(max_length=100, null=True)),
                ('committee_3', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
