# Generated by Django 4.0.1 on 2022-03-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_testbills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestBills',
            new_name='TestBill',
        ),
    ]
