# Generated by Django 4.0.1 on 2022-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_testbills_testbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbill',
            name='committee_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='committee_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='committee_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='sponsor_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='sponsor_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='sponsor_3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
