# Generated by Django 4.0.1 on 2022-03-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_testbill_committee_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbill',
            name='committee_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='committee_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='committee_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='sponsor_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='sponsor_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testbill',
            name='sponsor_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
