# Generated by Django 4.0.1 on 2022-03-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_testbill_committee_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbill',
            name='bill_id',
            field=models.CharField(default=999, max_length=250, primary_key=True, serialize=False),
        ),
    ]
