# Generated by Django 4.0.1 on 2022-04-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_testbill_bill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testbill',
            old_name='committee_1',
            new_name='chamber',
        ),
        migrations.RenameField(
            model_name='testbill',
            old_name='committee_2',
            new_name='committee',
        ),
        migrations.RenameField(
            model_name='testbill',
            old_name='committee_3',
            new_name='sponsor',
        ),
        migrations.RemoveField(
            model_name='testbill',
            name='sponsor_1',
        ),
        migrations.RemoveField(
            model_name='testbill',
            name='sponsor_2',
        ),
        migrations.RemoveField(
            model_name='testbill',
            name='sponsor_3',
        ),
    ]
