# Generated by Django 4.0.1 on 2022-04-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_delete_testbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=250, null=True)),
                ('chamber', models.CharField(blank=True, max_length=100)),
                ('committee', models.CharField(blank=True, max_length=100)),
                ('sponsor', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
