# Generated by Django 4.0.1 on 2022-04-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_testbill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestBill',
        ),
    ]
