# Generated by Django 4.0.1 on 2022-04-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_testbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committees',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='committees',
            name='committee',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Committees',
        ),
    ]
