# Generated by Django 4.0.1 on 2022-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_committees_bill_remove_committees_committee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_committee_id', models.CharField(max_length=100, null=True)),
                ('senate_committee_id', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
