# Generated by Django 4.0.1 on 2022-04-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_committee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
