# Generated by Django 4.0.1 on 2022-04-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_committee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
