# Generated by Django 4.0.1 on 2022-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_delete_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('thomas_id', models.CharField(max_length=100, null=True)),
                ('committee_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
